version: '3'

services:
  webserver:
    image: nginx:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"